from fastapi import APIRouter
from app.api.v1.endpoints import auth, majors, courses, admin, dictionary, organizations, course_covers, teaching_resources, resource_folders, reference_materials, reference_folders, questions, knowledge_graphs, exam_papers, exams, exam_students, students, teachers, course_outline, llm_configs, student_learning, ai_creation, ppt_creation, admin_dashboard, student_home, student_exams, student_interactions, learning_profile, personalized_learning, upload, llm_call_logs, course_qa, enrollments, admin_enrollments, teacher_grades

api_router = APIRouter()
api_router.include_router(upload.router, prefix="/upload", tags=["upload"])
api_router.include_router(auth.router, prefix="/auth", tags=["auth"])
api_router.include_router(organizations.router, prefix="/organizations", tags=["organizations"])
api_router.include_router(majors.router, prefix="/majors", tags=["majors"])
api_router.include_router(courses.router, prefix="/courses", tags=["courses"])
api_router.include_router(admin.router, prefix="/admin", tags=["admin"])
api_router.include_router(dictionary.router, prefix="/dictionary", tags=["dictionary"])
api_router.include_router(course_covers.router, prefix="/course-covers", tags=["course-covers"])
api_router.include_router(teaching_resources.router, prefix="/teacher/resources", tags=["teaching-resources"])
api_router.include_router(resource_folders.router, prefix="/teacher/folders", tags=["resource-folders"])
api_router.include_router(reference_materials.router, prefix="/teacher/references", tags=["reference-materials"])
api_router.include_router(reference_folders.router, prefix="/teacher/reference-folders", tags=["reference-folders"])
api_router.include_router(questions.router, prefix="/teacher/questions", tags=["questions"])
api_router.include_router(knowledge_graphs.router, prefix="/teacher/knowledge-graphs", tags=["knowledge-graphs"])
api_router.include_router(exam_papers.router, prefix="/teacher/exam-papers", tags=["exam-papers"])
api_router.include_router(exams.router, prefix="/teacher/exams", tags=["exams"])
api_router.include_router(exam_students.router, prefix="/teacher", tags=["exam-students"])
api_router.include_router(students.router, prefix="/student", tags=["students"])
api_router.include_router(teachers.router, prefix="/teacher", tags=["teachers"])
api_router.include_router(course_outline.router, prefix="/course-outline", tags=["course-outline"])
api_router.include_router(llm_configs.router, prefix="/admin/llm-configs", tags=["llm-configs"])
api_router.include_router(llm_call_logs.router, prefix="/admin/llm-call-logs", tags=["llm-call-logs"])
api_router.include_router(admin_dashboard.router, prefix="/admin/dashboard", tags=["admin-dashboard"])
api_router.include_router(student_learning.router, prefix="/student/learning", tags=["student-learning"])
api_router.include_router(student_home.router, prefix="/student/home", tags=["student-home"])
api_router.include_router(student_exams.router, prefix="/student", tags=["student-exams"])
api_router.include_router(student_interactions.router, prefix="/student", tags=["student-interactions"])
api_router.include_router(learning_profile.router, prefix="/student/learning-profile", tags=["learning-profile"])
api_router.include_router(personalized_learning.router, prefix="/student/personalized-learning", tags=["personalized-learning"])
api_router.include_router(course_qa.router, prefix="/student", tags=["course-qa"])
api_router.include_router(course_qa.router, prefix="/teacher", tags=["course-qa"])
api_router.include_router(ai_creation.router, prefix="/teacher/ai-creation", tags=["ai-creation"])
api_router.include_router(ppt_creation.router, prefix="/teacher/ppt-creation", tags=["ppt-creation"])

api_router.include_router(enrollments.router, prefix="/enrollments", tags=["enrollments"])
api_router.include_router(admin_enrollments.router, prefix="/admin/enrollments", tags=["admin-enrollments"])
api_router.include_router(teacher_grades.router, prefix="/teacher/grades", tags=["teacher-grades"])
